In [4]:
import numpy as np
import pandas as pd
df=pd.read_csv('iris.data',header=None)
print(df)
x=df.iloc[0:100,[0,1,2,3]].values
y=df.iloc[0:100,4].values
y=np.where(y=='Iris-setosa',0,1)
print(x)
print(y)

       0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [

In [5]:
x_train=np.empty((80,4))
x_test=np.empty((20,4))
y_train=np.empty(80)
y_test=np.empty(20)
x_train[:40],x_train[40:]=x[:40],x[50:90]
x_test[:10],x_test[10:]=x[40:50],x[90:100]
y_train[:40],y_train[40:]=y[:40],y[50:90]
y_test[:10],y_test[10:]=y[40:50],y[90:100]
print(x_train)
print(y_train)
print(x_test)
print(y_test)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.

In [6]:
#define function
def sigmoid(x):
    return 1/(1+np.exp(-x))

def activation(x,w,b):
    return sigmoid(np.dot(x,w)+b)

def update(x,y,w,b,eta):
    y_pred=activation(x, w, b)
    a=(y_pred-y_train)*y_pred*(1-y_pred)
    for i in range(4):
        w[i]-=eta*1/float(len(y))*np.sum(a*x[:,i])
    b-=eta*1/float(len(y))*np.sum(a)
    return w,b

In [7]:
#the initial value of w,b and eta
weights=np.ones(4)/10
bias=np.ones(1)/10
eta=0.1
#print(bias)
for _ in range(100):
    weights,bias=update(x_train,y_train,weights,bias,eta)
    
#print('weights=',weights,'bias=',bias)
#use test data to see the result
print(activation(x_test, weights, bias))

[0.20973161 0.32917075 0.24363451 0.270005   0.26828046 0.2690557
 0.21465776 0.25097853 0.20455037 0.23082375 0.8290824  0.82115024
 0.7755731  0.71536269 0.80403705 0.77275819 0.78693343 0.78525522
 0.6541637  0.78219052]
