In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1, 2, 3], [4, 5, 6],[3, 7, 9]])
arr2 = np.array([[2, 2, 13], [14, 5, 26],[3, 17, 19]])
newarr = np.multiply(arr1, arr2)
print(newarr)

[[  2   4  39]
 [ 56  25 156]
 [  9 119 171]]
